-- Insert home maintenance checklist items from BHG into reminders table
-- Monthly tasks
INSERT INTO public.reminders (title, description, frequency, difficulty, estimated_time, is_custom, enabled, family_id) VALUES
('Clean Furnace Filter', 'Clean the furnace filter to remove dust build-ups, make it easier to regulate your home''s temperature, and ultimately decrease energy bills.', 'monthly', 'Easy', '15 min', false, true, null),
('Vacuum Heat Registers and Vents', 'Vacuum heat registers and heat vents to maintain proper airflow.', 'monthly', 'Easy', '20 min', false, true, null),
('Check Air Vents for Blockages', 'Check that indoor and outdoor air vents are not blocked by debris or furniture.', 'monthly', 'Easy', '10 min', false, true, null),
('Check Water Softener', 'Check the water softener and replenish salt if necessary.', 'monthly', 'Easy', '10 min', false, true, null),
('Clean Garbage Disposal', 'Clean the garbage disposal by grinding ice cubes, then flushing with hot water and baking soda.', 'monthly', 'Easy', '10 min', false, true, null),
('Inspect Drain for Debris', 'Inspect tub and sink drains for debris; unclog if necessary.', 'monthly', 'Medium', '20 min', false, true, null),
('Flush Water Heater', 'Flush out hot water from the water heater to remove accumulated sediment.', 'monthly', 'Medium', '30 min', false, true, null),
('Test Safety Devices', 'Test smoke alarms, carbon monoxide detectors, and all ground-fault circuit interrupters. Check the gauge and expiration date on fire extinguishers.', 'monthly', 'Easy', '15 min', false, true, null),
('Inspect Electrical Cords', 'Inspect electrical cords for wear and damage.', 'monthly', 'Easy', '15 min', false, true, null),

-- Fall tasks
('Rake Leaves and Aerate Lawn', 'Rake leaves and aerate the lawn to prepare for winter.', 'yearly', 'Medium', '2 hours', false, true, null),
('Clean Gutters and Downspouts', 'Remove leaves and debris from gutters and downspouts.', 'yearly', 'Hard', '3 hours', false, true, null),
('Practice Pest Prevention', 'Keep firewood away from the house, trim shrubs, repair rotten or broken woodwork. Remove any wasp nests hanging from eaves or overhangs.', 'yearly', 'Medium', '2 hours', false, true, null),
('Winterize Exterior Plumbing', 'Drain and winterize exterior plumbing, including hoses and in-ground sprinkler systems.', 'yearly', 'Medium', '1 hour', false, true, null),
('Repair Driveway and Walkway Cracks', 'Mend cracks and gaps in the driveway and walkway.', 'yearly', 'Medium', '2 hours', false, true, null),
('Touch Up Exterior Paint', 'Touch up exterior siding and trim with paint.', 'yearly', 'Medium', '3 hours', false, true, null),
('Power-Wash Windows and Siding', 'Power-wash windows and siding to remove dirt and grime.', 'yearly', 'Medium', '2 hours', false, true, null),
('Inspect Roof for Damage', 'Inspect roofing for missing, loose, or damaged shingles and leaks.', 'yearly', 'Hard', '1 hour', false, true, null),
('Repair or Replace Siding', 'Inspect and repair or replace damaged siding.', 'yearly', 'Hard', '4 hours', false, true, null),
('Clean Window and Door Screens', 'Clean window and door screens to prepare for storage.', 'yearly', 'Easy', '1 hour', false, true, null),
('Replace Drafty Windows', 'Replace old, drafty windows for more energy-efficient models.', 'yearly', 'Hard', '1 day', false, true, null),
('Seal Window and Door Gaps', 'Seal cracks and gaps in windows and doors with caulk or weather stripping; replace if necessary.', 'yearly', 'Medium', '2 hours', false, true, null),
('Inspect Exterior Door Hardware', 'Inspect exterior door hardware; fix squeaky handles and loose locks.', 'yearly', 'Easy', '30 min', false, true, null),
('Insulate Outdoor Faucets', 'Wrap insulation around outdoor faucets and pipes in unheated garages.', 'yearly', 'Easy', '30 min', false, true, null),
('Inspect Heating System', 'Have the forced-air heating system inspected by a professional. Schedule an inspection in late summer or early fall before the heating season begins.', 'yearly', 'Easy', '2 hours', false, true, null),
('Check Fireplace', 'Check the fireplace for damage or hazards and clean fireplace flues. Have your fireplace professionally inspected.', 'yearly', 'Medium', '1 hour', false, true, null),
('Tune Up Appliances', 'Tune up major home appliances before the holidays.', 'yearly', 'Medium', '2 hours', false, true, null),
('Replace Detector Batteries', 'Replace the batteries in smoke and carbon monoxide detectors.', 'yearly', 'Easy', '15 min', false, true, null),
('Install Smoke Detectors', 'Install a smoke detector on every floor of your home, including the basement.', 'yearly', 'Medium', '1 hour', false, true, null),
('Clean Carpets', 'Deep clean carpets throughout the home.', 'yearly', 'Medium', '3 hours', false, true, null),
('Clean Dryer Vent', 'Vacuum lint from the dryer vent to prevent fire hazards.', 'yearly', 'Medium', '30 min', false, true, null),
('Check Water Heater for Leaks', 'Inspect the water heater for leaks and signs of damage.', 'yearly', 'Easy', '15 min', false, true, null),

-- Winter tasks
('Cover Air-Conditioning Unit', 'Cover your air-conditioning unit to protect it from winter weather.', 'yearly', 'Easy', '15 min', false, true, null),
('Inspect for Storm Damage', 'Inspect the roof, gutters, and downspouts for damage after storms.', 'weekly', 'Medium', '30 min', false, true, null),
('Stock Sidewalk Salt', 'Stock up on sidewalk salt and ice melt for winter weather.', 'yearly', 'Easy', '30 min', false, true, null),
('Check Basement for Leaks', 'Check the basement for leaks during thaws.', 'weekly', 'Easy', '15 min', false, true, null),
('Vacuum Bathroom Exhaust Fan', 'Vacuum bathroom exhaust fan grill to maintain proper ventilation.', 'quarterly', 'Easy', '10 min', false, true, null),
('Clean Refrigerator Coils', 'Vacuum refrigerator and freezer coils and empty and clean drip trays.', 'quarterly', 'Medium', '30 min', false, true, null),
('Clean Drains', 'Clean drains in sinks, tubs, showers, and dishwashers.', 'quarterly', 'Medium', '45 min', false, true, null),
('Set Mouse Traps', 'Set up mouse traps as needed to prevent rodent infestations.', 'monthly', 'Easy', '10 min', false, true, null),

-- Spring tasks
('Refinish Deck', 'Refinish the deck to protect it from weather damage.', 'yearly', 'Hard', '1 day', false, true, null),
('Fertilize Lawn', 'Apply fertilizer to your lawn to promote healthy growth.', 'yearly', 'Easy', '1 hour', false, true, null),
('Prune Trees and Shrubs', 'Prune trees and shrubs to maintain their health and appearance.', 'yearly', 'Medium', '2 hours', false, true, null),
('Spring Clean Screens', 'Clean window and door screens after winter storage.', 'yearly', 'Easy', '1 hour', false, true, null),
('Spring Gutter Cleaning', 'Remove leaves and debris from gutters and downspouts after winter.', 'yearly', 'Hard', '3 hours', false, true, null),
('Inspect Septic Tank', 'Have a professional inspect and pump the septic tank.', 'yearly', 'Easy', '2 hours', false, true, null),
('Spring Roof Inspection', 'Inspect roofing for missing, loose, or damaged shingles and leaks after winter.', 'yearly', 'Hard', '1 hour', false, true, null),
('Inspect Chimney', 'Inspect the chimney for damage from winter weather.', 'yearly', 'Medium', '30 min', false, true, null),
('Wash Windows', 'Clean windows inside and out for better visibility and appearance.', 'yearly', 'Medium', '2 hours', false, true, null),
('Spring Power-Wash Siding', 'Power-wash siding to remove winter grime and prepare for warmer months.', 'yearly', 'Medium', '2 hours', false, true, null),
('Spring Caulking Repair', 'Repair or replace caulking and weather stripping around windows, doors, and mechanicals.', 'yearly', 'Medium', '2 hours', false, true, null),
('Remove Faucet Insulation', 'Remove the insulation from outdoor faucets and check sprinkler heads.', 'yearly', 'Easy', '30 min', false, true, null),
('Clean Faucet Aerators', 'Clean faucet aerators and showerheads to remove mineral deposits.', 'yearly', 'Easy', '30 min', false, true, null),
('Change AC Filter', 'Change the air-conditioner filter to prepare for cooling season.', 'yearly', 'Easy', '10 min', false, true, null),
('Polish Wood Furniture', 'Polish wood furniture and dust light fixtures for spring cleaning.', 'yearly', 'Medium', '2 hours', false, true, null),
('Spring Detector Batteries', 'Replace the batteries in smoke and carbon monoxide detectors for spring.', 'yearly', 'Easy', '15 min', false, true, null),
('Inspect Caulking', 'Inspect sink, shower, and bath caulking for deterioration.', 'yearly', 'Easy', '15 min', false, true, null),
('Spring Dryer Vent Cleaning', 'Vacuum lint from the dryer vent for spring maintenance.', 'yearly', 'Medium', '30 min', false, true, null),
('Service Air Conditioning', 'Have the air-conditioning system serviced by a professional.', 'yearly', 'Easy', '1 hour', false, true, null),
('Spring Water Heater Maintenance', 'Drain or flush the water heater to remove sediment.', 'yearly', 'Medium', '1 hour', false, true, null),

-- Summer tasks
('Summer Dryer Vent Cleaning', 'Remove lint from your dryer vent during summer maintenance.', 'yearly', 'Medium', '30 min', false, true, null),
('Clean Kitchen Exhaust Fan', 'Clean kitchen exhaust fan filter to maintain proper ventilation.', 'quarterly', 'Medium', '20 min', false, true, null),
('Summer Refrigerator Maintenance', 'Clean refrigerator and freezer coils and empty and clean drip trays.', 'quarterly', 'Medium', '30 min', false, true, null),
('Check Dishwasher for Leaks', 'Inspect the dishwasher for leaks and proper operation.', 'quarterly', 'Easy', '15 min', false, true, null),
('Check Cabinet Areas for Leaks', 'Check around kitchen and bathroom cabinets and around toilets for leaks.', 'quarterly', 'Easy', '20 min', false, true, null),
('Replace Faucet Washers', 'Replace faucet and showerhead washers if needed to prevent drips.', 'yearly', 'Medium', '30 min', false, true, null),
('Seal Tile Grout', 'Seal tile grout to prevent water damage and maintain appearance.', 'yearly', 'Medium', '2 hours', false, true, null);