// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgwzmfgcuxtsrvcvahat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnd3ptZmdjdXh0c3J2Y3ZhaGF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMzY2NzIsImV4cCI6MjA2NTYxMjY3Mn0.nJ1QpeF8itnKLXr4Bfj63oB_lKxNR_TOSQmbPVQUuws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    storage: window.localStorage,
    storageKey: 'supabase.auth.token',
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});